packages:
  github.com/AskatNa/FoodStore/user-service:
    config:
      all: true
      recursive: true
      with-expecter: true
      filename: "mock_{{.InterfaceName | snakecase}}.go"
      dir: "{{.InterfaceDir}}/mocks"
      mockname: "{{.InterfaceName}}"
      outpkg: "mocks"
